/**
 * The public sponsorship index: a static page listing which employers actually
 * sponsor H-1B visas, from federal records, joined to how many jobs they have
 * open right now.
 *
 * Static HTML on purpose - it must be fast, search-indexable and shareable by
 * people who will never install anything. Regenerated by the nightly job.
 */
import { writeFileSync } from "node:fs";
import type { SupabaseClient } from "@supabase/supabase-js";

export interface IndexRow {
  company: string;
  matchedName: string;
  approvals: number;
  denials: number;
  fiscalYear: number;
  openJobs: number;
  usJobs: number;
}

const esc = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function renderPage(rows: IndexRow[], generatedAt: string, totals: {
  employers: number; federalRecords: number; openJobs: number; usJobsAtSponsors: number;
}): string {
  const fy = rows.length > 0 ? Math.max(...rows.map((r) => r.fiscalYear)) : 0;
  const body = rows.map((r) => {
    const rate = r.approvals + r.denials > 0
      ? Math.round((100 * r.approvals) / (r.approvals + r.denials))
      : 0;
    return `<tr data-name="${esc(r.company.toLowerCase())}">
  <td class="co">${esc(r.company)}<span class="matched">${esc(r.matchedName)}</span></td>
  <td class="n">${r.approvals.toLocaleString()}</td>
  <td class="n dim">${r.denials.toLocaleString()}</td>
  <td class="n dim">${rate}%</td>
  <td class="n">${r.openJobs.toLocaleString()}</td>
  <td class="n">${r.usJobs.toLocaleString()}</td>
</tr>`;
  }).join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Which companies actually sponsor H-1B visas — JobRadar</title>
<meta name="description" content="${totals.employers} employers with H-1B petitions on US federal record, matched to ${totals.usJobsAtSponsors.toLocaleString()} job openings they have live right now. Free, open source, updated daily.">
<meta property="og:title" content="Which companies actually sponsor H-1B visas">
<meta property="og:description" content="Federal H-1B filing records matched to live job openings. ${totals.usJobsAtSponsors.toLocaleString()} US jobs at employers who have actually sponsored.">
<style>
:root{--ink:#101828;--muted:#667085;--line:#e4e7ef;--bg:#f7f8fc;--card:#fff;--accent:#4f46e5;--ok:#067647}
*{box-sizing:border-box}
body{margin:0;font-family:Inter,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;color:var(--ink);
background:radial-gradient(900px 320px at 15% -80px,#eef2ff 0,rgba(238,242,255,0) 60%),var(--bg);line-height:1.5}
.wrap{max-width:1080px;margin:0 auto;padding:40px 20px 64px}
h1{font-size:32px;letter-spacing:-.6px;margin:0 0 8px;font-weight:800}
.lede{font-size:17px;color:#344054;max-width:70ch;margin:0 0 24px}
.stats{display:flex;gap:12px;flex-wrap:wrap;margin:0 0 24px}
.stat{background:var(--card);border:1px solid var(--line);border-top:3px solid var(--accent);
border-radius:10px;padding:12px 18px;min-width:150px;box-shadow:0 1px 2px rgba(16,24,40,.06)}
.stat b{display:block;font-size:22px;font-weight:800;letter-spacing:-.5px}
.stat span{font-size:12px;color:var(--muted)}
.note{background:#fffcf5;border:1px solid #fedf89;border-radius:10px;padding:14px 16px;
font-size:14px;color:#7a2e0e;max-width:80ch;margin:0 0 24px}
.note b{color:#7a2e0e}
#q{width:100%;max-width:420px;padding:10px 13px;border:1px solid var(--line);border-radius:8px;
font:inherit;font-size:14px;margin:0 0 14px;background:#fff}
table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);
border-radius:10px;overflow:hidden;box-shadow:0 1px 2px rgba(16,24,40,.06)}
th,td{padding:10px 14px;text-align:left;border-bottom:1px solid var(--line);font-size:14px}
th{background:#fbfcfe;font-size:12px;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);font-weight:700}
td.n,th.n{text-align:right;font-variant-numeric:tabular-nums}
td.dim{color:var(--muted)}
tr:last-child td{border-bottom:0}
tbody tr:hover{background:#fbfcff}
.co{font-weight:600}
.matched{display:block;font-weight:400;font-size:11.5px;color:var(--muted)}
footer{margin-top:32px;font-size:13px;color:var(--muted);max-width:80ch}
footer a{color:var(--accent)}
.cta{display:inline-block;margin:18px 0 0;background:var(--accent);color:#fff;text-decoration:none;
padding:11px 20px;border-radius:8px;font-weight:600;font-size:14px}
@media(max-width:640px){.wrap{padding:24px 12px 48px}h1{font-size:25px}th:nth-child(4),td:nth-child(4){display:none}}
</style>
</head>
<body>
<div class="wrap">
<h1>Which companies actually sponsor H-1B visas</h1>
<p class="lede">
Job sites tell you a posting "may offer sponsorship". This page tells you how many H-1B petitions
each employer <em>actually filed and won</em>, straight from US federal records — matched to the
jobs they have open right now.
</p>

<div class="stats">
<div class="stat"><b>${totals.employers.toLocaleString()}</b><span>employers with filings</span></div>
<div class="stat"><b>${totals.usJobsAtSponsors.toLocaleString()}</b><span>US jobs open at them now</span></div>
<div class="stat"><b>${totals.federalRecords.toLocaleString()}</b><span>federal records searched</span></div>
<div class="stat"><b>${totals.openJobs.toLocaleString()}</b><span>total jobs tracked</span></div>
</div>

<p class="note">
<b>Read this before you rely on it.</b> Counts come from the USCIS H-1B Employer Data Hub, latest
available fiscal year <b>FY${fy}</b>. A company absent from this list has no petitions in the records
we hold — that is evidence, not proof: a company can sponsor without recent filings, and a company
that sponsored before may not sponsor now. Employer names are matched exactly on a normalised name,
so a subsidiary filing under a different legal entity may be missed. Verify anything important at
<a href="https://www.uscis.gov/tools/reports-and-studies/h-1b-employer-data-hub">uscis.gov</a>.
</p>

<input id="q" type="search" placeholder="Filter companies…" autocomplete="off">

<table>
<thead><tr>
<th>Employer</th><th class="n">H-1Bs approved</th><th class="n">Denied</th>
<th class="n">Approval rate</th><th class="n">Jobs open</th><th class="n">US jobs</th>
</tr></thead>
<tbody id="rows">
${body}
</tbody>
</table>

<a class="cta" href="./">Search these jobs on JobRadar →</a>

<footer>
<p><b>Method.</b> Every job is pulled daily from the employer's own applicant tracking system via its
public API — no scraping, no aggregators. Sponsorship counts come from the USCIS H-1B Employer Data
Hub and are joined to employers by normalised name. Everything here is reproducible:
the code, the scoring weights and this page's generator are
<a href="https://github.com/SivaReddy123-C/sivareddy">open source</a>.</p>
<p>Generated ${esc(generatedAt.slice(0, 16).replace("T", " "))} UTC · Free while you job-hunt · No account needed to read this page.</p>
</footer>
</div>
<script>
// Filtering stays client-side and dependency-free so the page works everywhere.
const q = document.getElementById("q"), rows = [...document.querySelectorAll("#rows tr")];
q.addEventListener("input", () => {
  const v = q.value.trim().toLowerCase();
  for (const r of rows) r.style.display = !v || r.dataset.name.includes(v) ? "" : "none";
});
</script>
</body>
</html>`;
}

export async function buildSponsorPage(db: SupabaseClient, outPath: string): Promise<number> {
  const { data: companies, error } = await db
    .from("jr_companies")
    .select("id, name, sponsor_matched_name, h1b_approvals_recent, h1b_denials_recent, h1b_last_fiscal_year")
    .gt("h1b_approvals_recent", 0);
  if (error) throw new Error(`sponsor page query failed: ${error.message}`);

  const rows: IndexRow[] = [];
  let usJobsAtSponsors = 0;
  for (const c of companies ?? []) {
    const r = c as { id: string; name: string; sponsor_matched_name: string | null;
      h1b_approvals_recent: number; h1b_denials_recent: number | null; h1b_last_fiscal_year: number };
    const { count: openJobs } = await db.from("jr_job_postings")
      .select("id", { count: "exact", head: true })
      .eq("company_id", r.id).is("closed_at", null);
    const { count: usJobs } = await db.from("jr_job_postings")
      .select("id", { count: "exact", head: true })
      .eq("company_id", r.id).is("closed_at", null).eq("country", "us");
    usJobsAtSponsors += usJobs ?? 0;
    rows.push({
      company: r.name,
      matchedName: r.sponsor_matched_name ?? r.name,
      approvals: r.h1b_approvals_recent,
      denials: r.h1b_denials_recent ?? 0,
      fiscalYear: r.h1b_last_fiscal_year,
      openJobs: openJobs ?? 0,
      usJobs: usJobs ?? 0,
    });
  }
  rows.sort((a, b) => b.approvals - a.approvals);

  const { count: federalRecords } = await db.from("jr_sponsors").select("id", { count: "exact", head: true });
  const { count: openJobsTotal } = await db.from("jr_job_postings")
    .select("id", { count: "exact", head: true }).is("closed_at", null);

  const html = renderPage(rows, new Date().toISOString(), {
    employers: rows.length,
    federalRecords: federalRecords ?? 0,
    openJobs: openJobsTotal ?? 0,
    usJobsAtSponsors,
  });
  writeFileSync(outPath, html);
  return rows.length;
}
